protected/controllers/ActivityController.php
<?php

class ActivityController extends RController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'rights', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform actions
				'actions'=>array(
					'create',
					'update',
					'calendar',
					'showDay',
					'index',
					'view',
					'delete',
					'markAsCompleted',
					),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array(
					'admin',
			),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id, $activeTab = 'basic')
	{
		$baseUrl = Yii::app()->baseUrl;
		$cs = Yii::app()->getClientScript();
		$cs->registerScriptFile($baseUrl.'/js/views.js', CClientScript::POS_HEAD);

		$model = $this->loadModel($id);

		// Get staff data providers
		$staffDataProvider = $model->getRelatedData('StaffMember');
		$unrelatedStaffDataProvider = $model->getUnrelatedData('StaffMember');

		// Get vehicle data providers
		$vehicleDataProvider = $model->getRelatedData('Vehicle');
		$unrelatedVehicleDataProvider = $model->getUnrelatedData('Vehicle');

		// Get Client data providers
		$clientDataProvider = new CActiveDataProvider('Client', array(
			'criteria'=>array(
				'condition'=>"activity_id = $model->id"
			),
		));

		// Get recent unrelated clients. The criteria are the following
		// activity_id != $model->id
		// date (create_time) between 2 weeks ago and today
		/*
		$clientCriteria = new CDbCriteria;
		$clientCriteria->addNotInCondition('activity_id', array($model->id));
   	$lastTwoWeeks = date('Y-m-d', strtotime('-2 week'));

		// +1 day includes today's clients
   	$today = date('Y-m-d', strtotime("+1 day"));
		$clientCriteria->addBetweenCondition('create_time', $lastTwoWeeks, $today);

		$unrelatedClientDataProvider = new CActiveDataProvider('Client', array(
			'criteria'=>$clientCriteria,
		));
		*/
		
		// For client search
		$client=new Client('searchRecent', true);
		$client->unsetAttributes();  // clear any default values
		if(isset($_GET['Client']))
			$client->attributes=$_GET['Client'];


		// Render the view... finally!
		$this->render('view',array(
			'model'=> $model,
			'vehicle_list'=>$model->vehicles,
			'staff_list'=>$model->staff_members,
			'vehicleDataProvider'=>$vehicleDataProvider,
			'unrelatedVehicleDataProvider'=>$unrelatedVehicleDataProvider,
			'staffDataProvider'=>$staffDataProvider,
			'unrelatedStaffDataProvider'=>$unrelatedStaffDataProvider,
			'clientDataProvider'=>$clientDataProvider,
			'client'=>$client,
			'activeTab'=>$activeTab, //Set active tab for CTabView
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Activity;

		// Get staff and activity types lists
		$staff_list = CHtml::listdata(
			StaffMember::model()->findAll(),
			'id',
			'name'
		);
		$vehicle_list = CHtml::listdata(
			Vehicle::model()->findAll(),
			'id',
			'name'
		);
		$activity_types = CHtml::listdata(
			ActivityType::model()->findAll(),
			'id',
			'name'
		);


		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Activity']))
		{
			$model->attributes=$_POST['Activity'];
			if($model->save())
			{
			  Yii::log("Successfully created new activity: " . $model->id,
				"info",
				"application.controllers.ActivityController"
			    );
			  $this->redirect(array('view','id'=>$model->id));
			}
			else
			{
			  Yii::log("Failed to create Activity",
				"warning",
				"application.controllers.ActivityController"
				);
			}


		}

		$this->render('create',array(
			'model'=>$model,
			'activity_types'=>$activity_types,
			'vehicle_list'=>$vehicle_list,
			'staff_list'=>$staff_list,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Get extra data to list in create form
		$vehicles = Vehicle::model()->findAll();
		$staffMembers = StaffMember::model()->findAll();
		$activityTypes = ActivityType::model()->findAll();

		// List data
		$staff_list = CHtml::listdata($staffMembers, 'id', 'name');
		$vehicle_list = CHtml::listdata($vehicles, 'id', 'name');
		$activity_types = CHtml::listdata($activityTypes, 'id', 'name');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);



		if(isset($_POST['Activity']))
		{
			$model->attributes=$_POST['Activity'];

			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
			'activity_types'=>$activity_types,
			'vehicle_list'=>$vehicle_list,
			'staff_list'=>$staff_list,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			if($this->loadModel($id)->delete())
			{
			  Yii::log("Successfully deleted activity",
				"info",
				"application.controllers.ActivityController"
			    );
			}
			else
			{
				Yii::log("Failed to create Activity",
				  "warning",
				  "application.controllers.ActivityController"
				);
			}

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Activity('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Activity']))
			$model->attributes=$_GET['Activity'];

		$dataProvider=new CActiveDataProvider('Activity',
			array(
				'criteria'=>array(
					'order'=>'date DESC',
					),
			));


		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Activity('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Activity']))
			$model->attributes=$_GET['Activity'];

		$this->render('admin',array(
			'model'=>$model,
		));

	}

	/**
   * Displays a Activity Calendar
   */
	public function actionCalendar()
	{
	 /**
	  * If the user selected the month and year via drop down then it's set
	  * via post - otherwise they clicked a link, which means it's set by get.
	  * If the next / previous month links were clicked the get value will be filled
	  * otherwise it will be NULL (like clicking the calendar link in main menu) and the
	  * class will account for this and set the default current month and year.
	  */

    if (isset($_POST['month']) && isset($_POST['year']))
    {
     	$month = $_POST['month'];
     	$year = $_POST['year'];
    }
    else if(isset($_GET['month']) && isset($_GET['year']))
    {
     	$month = $_GET['month'];
     	$year = $_GET['year'];
    }

    else
    {
    	$month = null;
    	$year = null;
    }

    // Create calendar and set css file
    $calendar=new Calendar(
    	$month,
     	$year,
			Yii::app()->theme->baseUrl . '/css/calendar.css'
		);

     // Create links for the control menu
     $calendar->nextMonthUrl = $this->createUrl('activity/calendar', array(
         'month'=>$calendar->nextMonth,
         'year'=>$calendar->yearNextMonth)
     );
     $calendar->previousMonthUrl = $this->createUrl('activity/calendar', array(
         'month'=>$calendar->previousMonth,
         'year'=>$calendar->yearPreviousMonth)
     );
     $calendar->storePreviousLink = CHtml::link("< Previous Month", $calendar->previousMonthUrl);
     $calendar->storeNextLink = CHtml::link("Next Month >", $calendar->nextMonthUrl);
     $this->render('calendar',array('calendar'=>$calendar));
	}

	/**
	 * Displays a list of activities for a given date
	 * @param string $date to display activities
	 */
	public function actionShowDay($date = null)
	{
		// If the user gets here by typing the view name in the browser's nav bar
		// without specifying a day, set today as date to show activities
		if ($date === null)
			$date = date('Y-m-d', time());

		$dataProvider=new CActiveDataProvider('Activity', array(
				'criteria'=>array(
					'condition'=>"date = '$date'",
					'order'=>'time',
				)
			)
		);

		$this->render('showDay',array(
			'dataProvider'=>$dataProvider,
			'date'=>$date,
		));
	}

	/**
	 * Sets activity as completed
	 * @param int id activity id
	 */
	public function actionMarkAsCompleted($id)
	{
		$model = $this->loadModel($id);

		$model->completed = 1;

		if ($model->save())
		{
			Yii::app()->user->setFlash('success', "Activity $model->name marked as " .
					"completed");
			$this->redirect(array('index'));
		}

		else
		{
			Yii::app()->user->setFlash('error', "There was an error while marking ' .
					'$model->name as completed");
			$this->redirect(array('index'));
		}

	}


	/**

protected/controllers/VehicleController.php
<?php

class VehicleController extends RController
{
	
	/**
	 * @var private property containing the associated Activity model instance.
	 */
	private $_activity = null;
	
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'rights', // perform access control for CRUD operations
			'activityContext + addToActivity removeFromActivity',
		);
	}

	/**
	 * In-class defined filter method, configured for use in the above
   * filters() method
   * It is called before the actionCreate() action method is run in
   * order to ensure a proper activity context
   */
	public function filterActivityContext($filterChain)
	{
		//set the project identifier based on either the GET or POST input
	  //request variables, since we allow both types for our actions
		$activityId = null;
		if(isset($_GET['activityId']))
			$activityId = $_GET['activityId'];
		
		else
			if(isset($_POST['activityId']))
				$activityId = $_POST['activityId'];
		
		$this->loadActivity($activityId);
		//complete the running of other filters and execute the requested action
		
		$filterChain->run();
	} 
	
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
//	public function accessRules()
//	{
//		return array(
//			array('allow', // allow authenticated user to perform 'create' and 'update' actions
//				'actions'=>array(
//					'create',
//					'update', 
//					'addToActivity', 
//					'removeFromActivity',
//					'index',
//					'view'
//				),
//				'users'=>array('@'),
//			),
//			array('allow', // allow admin user to perform 'admin' and 'delete' actions
//				'actions'=>array('admin','delete'),
//				'users'=>array('admin'),
//			),
//			array('deny',  // deny all users
//				'users'=>array('*'),
//			),
//		);
//	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Vehicle;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Vehicle']))
		{
			$model->attributes=$_POST['Vehicle'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 * @param integer $activityId the id of the activity to redirect to after
	 * the update. If $activityId is 0 the redirect is to the vehicle view
	 * Redirecting to vehicle view means the user updated the vehicle from the
	 * vehicle view. Redirecting to the activity view means the user updated the
	 * vehicle from the activity view.
	 */
	public function actionUpdate($id, $activityId = 0)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Vehicle']))
		{
			$model->attributes=$_POST['Vehicle'];
			if($model->save())
			{
				// Redirect to client view 
				if ($activityId == 0)
					$this->redirect(array('view','id'=>$model->id));
				
				// Redirect to activity view
				else
					$this->redirect(array(
							'/activity/view', 
							'id'=>$activityId,
							'activeTab'=>'vehicles'
							)
					);
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Vehicle');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Vehicle('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Vehicle']))
			$model->attributes=$_GET['Vehicle'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	/**
	 * Adds a staff member to an activity
	 * @param int $id vehicle id
	 */
	public function actionAddToActivity($id)
	{
		$model = $this->loadModel($id);
		
		//TODO whe are redirecting instead of just refreshing the grids... it has
		// to be done with AJAX, still have to lear it :(	
		if($model->associateVehicleWithActivity($this->_activity->id))
		{
				Yii::app()->user->setFlash('success', "Vehicle '$model->name' added to 
				activity");
				$this->redirect(array('/activity/view','id'=>$this->_activity->id, 'activeTab'=>'vehicles'));
		}
		
		else
		{
			Yii::app()->user->setFlash('error', "There was an error while 
				adding Vehicle '$model->name' to activity");
			$this->redirect(array('/activity/view','id'=>$this->_activity->id, 'activeTab'=>'vehicles'));
		}
	}
	
	/**
	 * Remove vehicle from activity
	 * @param int id Activity id
	 * @param int vehicleId vehicle id to dissociate from activity
	 */
	public function actionRemoveFromActivity($id)
	{
		$model = $this->loadModel($id);
		
   		// Disassociate
   		if($model->disassociateVehicleWithActivity($this->_activity->id))
   		{
			Yii::app()->user->setFlash('success', "Vehicle '$model->name' removed from 
				activity");
			$this->redirect(array('/activity/view','id'=>$this->_activity->id, 'activeTab'=>'vehicles'));
		}
		
		// Failed to disassociate
		else
		{
			Yii::app()->user->setFlash('error', "There was an error while 
				removing Vehicle '$model->name' from activity");
			$this->redirect(array('view','id'=>$id, 'activeTab'=>'vehicles'));
		}
	}
	

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Vehicle::model()->findByPk((int)$id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	
	/**
	 * Protected method to load the associated Activity model class
	 * @activity_id the primary identifier of the associated Activity
	 * @return object the Activity data model based on the primary key
	 */
	protected function loadActivity($activityId)
	{
		//if the actvity property is null, create it based on input id
		if($this->_activity===null)
		{
			$this->_activity=Activity::model()->findbyPk($activityId);
			if($this->_activity===null)
			{
				throw new CHttpException(404,'The requested activity does not exist.');
			}
		}
		
		return $this->_activity;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='vehicle-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/activity/_basic.php
<?php $this->widget('TDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'date',
		'time',
		array( // display 'Activity.type_id' using an expression
            'name'=>'type_id',
            'value'=> $model->type->name,
        ),
		'completedValue',
		'notes',
	),
)); ?>

protected/views/activity/_client.php
<?php
Yii::app()->clientScript->registerScript('Client', "
$('#add-client-link').click(function(){
	$('#add-client').toggle();
	return false;
});"
);
?>

<div id="related-clients">
<?php
// For some reason (bug?) I can't have this gridview as a TGridView object
// because some costume css is not applied.
$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'related-client-grid',
  'dataProvider'=>$clientDataProvider,
  'columns'=>array(

  	// Link column for client names
  	array(
  		'class' =>'CLinkColumn',
  		'header'=> 'Name',
  		'labelExpression'=> '$data->name',
  		'urlExpression'=>'Yii::app()->createUrl("/client/$data->id")'
		),

		// Other client properties
		'arrived',
		'pax',
		'number_children',
		array(
			'name'=>'hotel_id',
			'value'=>'CHtml::encode($data->getHotelName())'
		),
		array(
			'name'=>'agency_id',
			'value'=>'CHtml::encode($data->getTravelAgencyName())'
		),
		array(
			'name'=>'country_id',
			'value'=>'CHtml::encode($data->getCountryName())',
		),
		array(
			'name' => CHtml::encode('totalDirectOrVoucher'),
			'value' =>'CHtml::encode($data->getTotalDirectOrVoucher())'
		),
		array(
			'name'=>CHtml::encode('debt'),
			'value'=>'$data->getDebt()',
		),
		array(
			'name'=>CHtml::encode('Prepaid'),
			'value'=>'$data->value_prepayed'
		),
		'notes',


		// Actions
		array(
			'class'=>'CButtonColumn',
			'template'=>'{markAsArrived}{update}{move}{delete}',
			'header'=>'Options',
			'htmlOptions'=>array('width'=>'70px'),

			'viewButtonUrl'=>'Yii::app()->createUrl("/client/view", ' .
					'array("id"=>$data["id"]))',
			'viewButtonLabel'=> Yii::t('ToolTips', 'View Client'),

			'updateButtonUrl'=>'Yii::app()->createUrl("/client/update", ' .
					'array("id"=>$data["id"], "activityId"=>'."$model->id".'))',
			'updateButtonLabel'=>Yii::t('ToolTips', 'Update Client'),

			'deleteButtonUrl'=>'Yii::app()->createUrl("/client/removeFromActivity",' .
					' array("id"=>$data["id"], "activityId"=>'."$model->id".'))',
			'deleteButtonLabel'=>Yii::t('ToolTips', 'Remove Client'),
			'deleteButtonImageUrl'=>Yii::app()->baseUrl.'/images/list-remove.png',
			'deleteConfirmation'=> false,

			// Update available seats
			'afterDelete'=>'refreshOccupationRate',

			// Move button button
			'buttons'=> array(
				'move'=>array(
					'label'=>Yii::t('ToolTips', 'Copy/Move Client'),
					'imageUrl'=> Yii::app()->baseUrl.'/images/go-next.png',
					'url'=>'Yii::app()->createUrl("/client/move", array("id"=>$data["id"],' .
							' "activityId"=>'."$model->id".'))',
					),
				'markAsArrived'=>array(
					'label'=>Yii::t('ToolTips', 'Mark as Arrived'),
					'imageUrl'=> Yii::app()->baseUrl.'/images/mail-signed-verified.png',
					'url'=>'Yii::app()->createUrl("/client/markAsArrived", array("id"=>$data["id"],' .
							' "activityId"=>'."$model->id".'))',
				),
			),

		),
)));

// Extra detail about clients
$this->widget('TDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'totalAdults',
		'totalChildren',
		'totalPax',
		'totalCashDirect',
		'totalCashCredit',
		'totalCash',
	),
));
?>
</div><!-- End related clients -->


<?php echo CHtml::link('+ Add Clients','#',array('id'=>'add-client-link')); ?>
<div id="add-client" style="display:none" >

<?php
$this->widget('TGridView', array(
	'id'=>'unrelated-client-grid',
  'dataProvider'=>$client->search(true),
  'filter'=>$client,
	'columns'=>array(
		'name',
		'pax',
		'number_children',
		'telephone',
		array(
			'name'=>'hotel_id',
			'value'=>'CHtml::encode($data->getHotelName())'
		),
		array(
			'name'=>'agency_id',
			'value'=>'CHtml::encode($data->getTravelAgencyName())'
		),
		array(
			'name'=>'country_id',
			'value'=>'CHtml::encode($data->getCountryName())',
		),

		array(
			'class'=>'CButtonColumn',
			'template'=>'{view}{update}{add}',
			'header'=>'Options',
			'updateButtonUrl'=>'Yii::app()->createUrl("/client/update", ' .
					'array("id"=>$data["id"], "activityId"=>'."$model->id".'))',
			'updateButtonLabel'=>Yii::t('ToolTips', 'Update Client'),

			// Update available seats
			'afterDelete'=>'refreshOccupationRate',

			// Move button
			'buttons'=> array(
				'add'=>array(
						'label'=>Yii::t('ToolTips', ' Add to Actvivity'),
						'imageUrl'=> Yii::app()->baseUrl.'/images/list-add.png',
						'url'=>'Yii::app()->createUrl(' .
								'"/client/copyToActivity", ' .
								'array("id"=>$data["id"], ' .
								'"newActivityId"=>'."$model->id".',' .
								'"activityId"=>'."$model->id".'))',
					),
			),
	))));

echo CHtml::link('+ Add New Client', Yii::app()->createUrl(
	"/client/create",
	array("activityId"=>$model->id
	)));
?>
</div><!-- end add-client -->

protected/views/activity/_vehicle.php
<?php
Yii::app()->clientScript->registerScript('Vehicle', "
$('#add-vehicle-link').click(function(){
	$('#add-vehicle').toggle();
	return false;
});"
);
?>

<div id="related-vehicles">
<?php
$this->widget('TGridView', array(
	'id'=>'busy-vehicle-grid',
    'dataProvider'=>$vehicleDataProvider,
    'columns'=>array(

    // Link column for vehicle names
  	array(
  		'class' =>'CLinkColumn',
  		'header'=> 'Name',
  		'labelExpression'=> '$data->name',
  		'urlExpression'=>'Yii::app()->createUrl("/vehicle/$data->id")'
		),

		//Other vehicle properties
		'type',
		'capacity',

		// Actions
		array(
			'class'=>'CButtonColumn',
			'template'=>'{update}{delete}',
			'header'=>'Options',
			'viewButtonUrl'=>'Yii::app()->createUrl("/vehicle/view", ' .
					'array("id"=>$data["id"]))',

			'updateButtonUrl'=>'Yii::app()->createUrl("/vehicle/update", ' .
					'array("id"=>$data["id"], "activityId"=>'."$model->id".'))',

			'deleteButtonLabel'=>'Remove from Activity',

			'deleteButtonUrl'=>'Yii::app()->createUrl(' .
					'"/vehicle/removeFromActivity", ' .
					'array("id"=>$data["id"], "activityId"=>'."$model->id".'))',

      		'deleteButtonImageUrl'=>Yii::app()->baseUrl.'/images/list-remove.png',

			'deleteConfirmation'=> false,

			// Updates available seats and available vehicles
			'afterDelete'=>'afterVehicleDelete',
			),
)));
?>

</div><!--End related-vehicles -->

<?php echo CHtml::link('+ Add Vehicle','#',array('id'=>'add-vehicle-link')); ?>
<div id="add-vehicle" style="display:none" >

<?php

// Gridview with unrelated vehicles
$this->widget('TGridView', array(
	'id'=>'available-vehicle-grid',
  'dataProvider'=>$unrelatedVehicleDataProvider,
  'columns'=>array(

  	// Link column for vehicle names
  	array(
  		'class' =>'CLinkColumn',
  		'header'=> 'Name',
  		'labelExpression'=> '$data->name',
  		'urlExpression'=>'Yii::app()->createUrl("/vehicle/$data->id")'
		),

		//Other vehicle properties
		'type',
		'capacity',

		array(
			'class'=>'CButtonColumn',
			'template'=>'{update}{move}',
			'header'=>'Options',
			'viewButtonUrl'=>'Yii::app()->createUrl("/vehicle/view", ' .
					'array("id"=>$data["id"]))',

			'updateButtonUrl'=>'Yii::app()->createUrl("/vehicle/update", ' .
					'array("id"=>$data["id"], "activityId"=>'."$model->id".'))',

				// Move button
			'buttons'=> array(
				'move'=>array(
						'label'=>Yii::t('ToolTips', 'Add Vehicle to Activity'),
						'imageUrl'=> Yii::app()->baseUrl.'/images/list-add.png',
						'url'=>'Yii::app()->createUrl("/vehicle/addToActivity", ' .
								'array("id"=>$data["id"], "activityId"=>'."$model->id".'))',
//						'click'=>'function(link, success, data){if(success) ' .
//							'$.fn.yiiGridView.update("busy-vehicle-grid");}',
				),

			),
		),

)));

?>
</div><!-- search-form -->