protected/models/Client.php
<?php

/**
 * This is the model class for table "tbl_client".
 *
 * The followings are the available columns in table 'tbl_client':
 * @property integer $id
 * @property string $name
 * @property string $telephone
 * @property string $email
 * @property integer $hotel_id
 * @property integer $room_number
 * @property integer $pax
 * @property integer $activity_id
 * @property float $value_payed_adult
 * @property float $value_payed_children
 * @property float $value_prepayed
 * @property string $notes
 * @property string $create_time
 * @property string $update_time
 * @property string $country_id
 * @property integer $number_children
 * @property integer $create_user_id
 * @property integer $paymment_type
 * @property string voucher
 * @property integer arrived
 *
 * The followings are the available model relations:
 * @property Activity $activities
 * @property TravelAgency $agency
 * @property Hotel $hotel
 * @property User $user
 */
class Client extends TourManagerActiveRecord
{
	private $_arrived_options;
	/**
	 * @var paymment type: direct paymment
	 */
	const DIRECT = 0;

	/**
	 * @var paymment type: credit paymment
	 */
	const CREDIT = 1;

	/**
	 * Returns the static model of the specified AR class.
	 * @return Client the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_client';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, pax', 'required'),
			array('hotel_id, room_number, agency_id, pax, number_children, country_id, paymment_type, activity_id', 'numerical', 'integerOnly'=>true),
			array('hotel_id, room_number, agency_id, pax, number_children', 'numerical', 'min'=>0),
			array('value_payed_adult, value_payed_children, value_prepayed', 'numerical', 'min'=>0.0),
			array('name, voucher', 'length', 'max'=>64),
			array('telephone', 'length', 'max'=>32),
			array('email', 'length', 'max'=>256),
			array('arrived', 'length', 'max'=>6),
			array('email', 'email'),
			array('notes, create_time, update_time', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, telephone, email, hotel_id, agency_id, pax, value_payed, notes, country_id, number_children, voucher, arrived', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'agency' => array(self::BELONGS_TO, 'TravelAgency', 'agency_id'),
			'hotel' => array(self::BELONGS_TO, 'Hotel', 'hotel_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'user'=>array(self::BELONGS_TO, 'User', 'create_user_id'),
			'activity'=>array(self::BELONGS_TO, 'Activity', 'activity_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'telephone' => 'Phone',
			'email' => 'Email',
			'hotel_id' => 'Hotel',
			'room_number' => 'Room #',
			'agency_id' => 'Agency',
			'pax' => 'Adults',
			'value_payed_children' => 'Value Payed (Children)',
			'value_payed_adult' => 'Value Payed (Adults)',
			'notes' => 'Notes',
			'create_time' => 'Create Time',
			'update_time' => 'Update Time',
			'country_id' => 'Country',
			'number_children' => 'Children',
			'value_prepaid' => 'Prepaid value',
			'hotelName' => 'Hotel',
			'travelAgencyName' => 'Travel Agency',
			'countryName' => 'Country',
			'paymment_type' => 'Paymment Type',
			'voucher' => 'Voucher',
			'totalDirect' => 'Total Direct',
			'totalDirectOrVoucher' => '€/V',
			'totalCredit' => 'Total Credit',
			'debt' => 'Debt',
			'arrived' => 'Arrived',
			'arrivedStatus' => 'Arrived'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @param $recent true if the method should only search recent clients
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search($recent = false)
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;


		// Search agency by name
		$agency = TravelAgency::model()->findByAttributes(array('name'=>$this->agency_id));
		if(isset($agency))
		{
	  		$criteria->compare('agency_id', $agency->id, true);
		}
		else $criteria->compare('agency_id', $this->agency_id, true);

		// Search Hotel by name
		$hotel = Hotel::model()->findByAttributes(array('name'=>$this->hotel_id));
		if(isset($hotel))
		{
		  $criteria->compare('hotel_id',$hotel->id, true);
		}
		else $criteria->compare('hotel_id', $this->hotel_id, true);
		
		$country = Country::model()->findByAttributes(array('name'=>$this->country_id));
		if(isset($country))
		{
			$criteria->compare('country_id', $country->id, true);
		}
		else $criteria->compare('country_id', $this->country_id, true);

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('telephone',$this->telephone,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('room_number',$this->room_number);
		$criteria->compare('pax',$this->pax);
		$criteria->compare('value_payed_adult',$this->value_payed_adult);
		$criteria->compare('value_payed_children',$this->value_payed_children);
		$criteria->compare('value_prepayed',$this->value_prepayed);
		$criteria->compare('notes',$this->notes,true);
		$criteria->compare('create_time',$this->create_time,true);
		$criteria->compare('update_time',$this->update_time,true);
		$criteria->compare('number_children',$this->number_children, true);
		$criteria->compare('paymment_type',$this->paymment_type, true);
		$criteria->compare('voucher',$this->voucher, true);
		$criteria->compare('arrived',$this->arrived, true);

		// Search only recent clients so that they are shown in main activity view
		// This causes less overhead
		if ($recent === true)
		{
			$lastTwoWeeks = date('Y-m-d', strtotime('-2 weeks'));

			// +1 day includes today's clients
   		$today = date('Y-m-d', strtotime("+1 day"));
			$criteria->addBetweenCondition('create_time', $lastTwoWeeks, $today);
		
		}

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}

	public function getTravelAgencyName()
	{
		if (isset($this->agency))
			return $this->agency->name;

		return 'Not set';
	}

	public function getHotelName()
	{
		if (isset($this->hotel))
			return $this->hotel->name;

		return 'Not set';
	}

	public function getCountryName()
	{
		if (isset($this->country))
			return $this->country->name;

		return 'Not Set';
	}

  /**
   * Replaces Agencies and Hotel names by their id's before validating forms
   */
  public function beforeValidate()
  {
    // Replace strings with primary keys for hotels and agencies
    if (isset($this->agency_id))
    {
    	$agency = TravelAgency::model()->findByAttributes(array('name'=> $this->agency_id));
    	if (isset($agency))
    		$this->agency_id = $agency->id;
    }

	  if (isset($this->hotel_id))
	  {
	  	$hotel = Hotel::model()->findByAttributes(array('name'=> $this->hotel_id));
	  	if (isset($hotel))
	  		$this->hotel_id = $hotel->id;
	  }

    return parent::beforeValidate();
  }


	/**
	 * @return array with payment types (integer) and their descriptions
	 */
	public function getPaymmentTypes()
	{
		return array(
			self::DIRECT => 'Direct',
			self::CREDIT => 'Credit',
		);

	}

	/**
	 * @return string paymment type name
	 */
	public function getPaymmentTypeName()
	{
	  $paymmentTypes = $this->getPaymmentTypes();
	  return isset($paymmentTypes[$this->paymment_type]) ? $paymmentTypes[$this->paymment_type] :
	    "unknown paymment type ({$this->paymment_type})" ;
	}

	/**
	 * Calculate the total price payed with this client reservation direct
	 * @return float total price payed with this client reservation
	 */
	public function getTotalDirect()
	{
		$total = 0.00;
		$totalAdults = 0;
		$totalChildren = 0;

		if (isset($this->pax))
			$totalAdults = $this->pax;

		if (isset($this->number_children))
			$totalChildren = $this->number_children;

		// Check paymment type and calculate the total value payed
		if ($this->paymment_type == self::DIRECT)
		{
			$total = ($totalAdults * $this->value_payed_adult) +
				($totalChildren * $this->value_payed_children);
		}

		return $total;
	}

	/**
	 * Calculate the total price payed with this client reservation credit
	 * @return float total price payed with this client reservation
	 */
	public function getTotalCredit()
	{
		$total = 0.00;
		$totalAdults = 0;
		$totalChildren = 0;

		if (isset($this->pax))
			$totalAdults = $this->pax;

		if (isset($this->number_children))
			$totalChildren = $this->number_children;

		if($this->paymment_type == self::CREDIT)
		{
			$total = ($totalAdults * $this->value_payed_adult) +
				($totalChildren * $this->value_payed_adult);
		}

		return $total;
	}

	/**
	 * @return string The value payed by the client if we are in
	 * presence of a direct sale or a the voucher number if a credit sale
	 */
	public function getTotalDirectOrVoucher()
	{
		$total = $this->getTotalDirect();

		if ($total == 0)
			return $this->voucher;

		else return '€ '.(string)$total;
	}

	/**
	 * @return float the value the client has in debt
	 */
	public function getDebt()
	{
		if ($this->paymment_type == self::DIRECT)
			return $this->getTotalDirect() - $this->value_prepayed;

		else return 0.00;
	}

	/**
	 * @return array with yes or no for arrived field
	 */
	public function getArrivedOptions()
	{

protected/views/client/_contacts.php
<div class="row">
	<?php echo $form->labelEx($model,'telephone'); ?>
	<?php echo $form->textField($model,'telephone',array('size'=>32,'maxlength'=>32)); ?>
	<?php echo $form->error($model,'telephone'); ?>
</div>

<div class="row">
	<?php echo $form->labelEx($model,'email'); ?>
	<?php echo $form->textField($model,'email',array('size'=>32,'maxlength'=>256)); ?>
	<?php echo $form->error($model,'email'); ?>
</div>

<div class="row">
		<?php echo $form->labelEx($model,'hotel_id'); ?>
		<?php
			$this->widget('zii.widgets.jui.CJuiAutoComplete', array(
	      	'source'=>$hotels,
	      	'model'=>$model,
	      	'attribute'=>'hotel_id',
	    	));
		?>
		<?php echo $form->error($model,'hotel_id'); ?>
</div>

<div class="row">
		<?php echo $form->labelEx($model,'room_number'); ?>
		<?php echo $form->textField($model,'room_number', array('size'=>3, 'maxlenght'=>4)); ?>
		<?php echo $form->error($model,'room_number'); ?>
	</div>

<div class="row">
		<?php echo $form->labelEx($model,'agency_id'); ?>
		<?php
			$this->widget('zii.widgets.jui.CJuiAutoComplete', array(
	      	'source'=>$agencies,
	      	'model'=>$model,
	      	'attribute'=>'agency_id',
	    	));
		?>
		<?php echo $form->error($model,'agency_id'); ?>
</div>

<div class="row">
	<?php echo $form->labelEx($model,'country_id'); ?>
	<?php echo $form->dropDownList($model, 'country_id', CHtml::listdata(Country::model()->findAll(), 'id', 'name'), array('options' => array('122'=>array('selected'=>true)))); ?>
  	<?php echo $form->error($model,'country_id'); ?>
</div>

protected/views/client/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'client-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>32,'maxlength'=>64)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'pax'); ?>
		<?php echo $form->textField($model,'pax', array('size'=>3, 'maxlenght'=>4)); ?>
		<?php echo $form->error($model,'pax'); ?>
		<span class="hint"><?php echo "Only adults should be introduced here"; ?></span>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'number_children'); ?>
		<?php echo $form->textField($model,'number_children', array('size'=>3, 'maxlenght'=>4)); ?>
		<?php echo $form->error($model,'number_children'); ?>
	</div>


<?php
	// This form is used by activity as well, so we need to give absolute paths
	// within the app so the view file can be resolved
	$this->widget('zii.widgets.jui.CJuiAccordion', array(
    'panels'=>array(
        'Contacts and Nationality'=>$this->renderPartial('/client/_contacts',
        	array(
				'model'=>$model,
				'form'=>$form,
				'hotels'=>$hotels,
				'agencies'=>$agencies,
			),
		true),
        'Payments and Notes'=>$this->renderPartial('/client/_payments',
        array(
			'model'=>$model,
			'form'=>$form,
			),
		true),

    ),
    // additional javascript options for the accordion plugin
    'options'=>array(
        //'animated'=>'bounceslide',
        'collapsible'=>true,
    ),
));

?>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/client/_payments.php
<div class="row">
		<?php echo $form->labelEx($model,'paymment_type'); ?>
		<?php echo $form->dropDownList($model, 'paymment_type', $model->getPaymmentTypes()); ?>
		<?php echo $form->error($model,'paymment_type'); ?>
</div>

<div class="row">
		<?php echo $form->labelEx($model,'voucher'); ?>
		<?php echo $form->textField($model, 'voucher', array('size'=>32, 'maxlength'=>64)); ?>
		<?php echo $form->error($model,'voucher'); ?>
</div>

<div class="row">
	<?php echo $form->labelEx($model,'value_payed_adult'); ?>
	<?php echo $form->textField($model,'value_payed_adult', array('size'=>3, 'maxlenght'=>4)); ?>
	<?php echo $form->error($model,'value_payed_adult'); ?>
</div>

<div class="row">
	<?php echo $form->labelEx($model,'value_payed_children'); ?>
	<?php echo $form->textField($model,'value_payed_children', array('size'=>3, 'maxlenght'=>4)); ?>
	<?php echo $form->error($model,'value_payed_children'); ?>
</div>

<div class="row">
	<?php echo $form->labelEx($model,'value_prepayed'); ?>
	<?php echo $form->textField($model,'value_prepayed', array('size'=>3, 'maxlenght'=>4)); ?>
	<?php echo $form->error($model,'value_prepayed'); ?>
</div>

<div class="row">
	<p id="total_cash"></p>
	<script type="text/javascript">
	getTotalPayed();
	</script>
</div>

<div class="row">
	<?php echo $form->labelEx($model,'arrived'); ?>
	<?php echo $form->dropDownList($model,'arrived', $model->arrivedOptions); ?>
	<?php echo $form->error($model,'arrived'); ?>
</div>

<div class="row">
	<?php echo $form->labelEx($model,'notes'); ?>
	<?php echo $form->textArea($model,'notes',array('rows'=>6, 'cols'=>50)); ?>
	<?php echo $form->error($model,'notes'); ?>
</div>

protected/views/client/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id', array('size'=>3)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>32,'maxlength'=>64)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'telephone'); ?>
		<?php echo $form->textField($model,'telephone',array('size'=>32,'maxlength'=>32)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>32,'maxlength'=>256)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pax'); ?>
		<?php echo $form->textField($model,'pax', array('size'=>3)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'number_children'); ?>
		<?php echo $form->textField($model,'number_children', array('size')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'value_payed_adult'); ?>
		<?php echo $form->checkBox($model,'value_payed_adult'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'value_payed_children'); ?>
		<?php echo $form->checkBox($model,'value_payed_children'); ?>
	</div>


	<div class="row">
		<?php echo $form->label($model,'value_prepayed'); ?>
		<?php echo $form->checkBox($model,'value_prepayed'); ?>
	</div>
	<div class="row">
		<?php echo $form->label($model,'hotel_id'); ?>
		<?php echo $form->textField($model,'hotel_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'room_number'); ?>
		<?php echo $form->textField($model,'room_number', array('size'=>3)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'agency_id'); ?>
		<?php echo $form->textField($model,'agency_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'notes'); ?>
		<?php echo $form->textArea($model,'notes',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'country_id'); ?>
		<?php echo $form->textField($model,'country_id'); ?>
	</div>


	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/client/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->name), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('telephone')); ?>:</b>
	<?php echo CHtml::encode($data->telephone); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hotel_id')); ?>:</b>
	<?php echo CHtml::encode($data->hotelName); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('room_number')); ?>:</b>
	<?php echo CHtml::encode($data->room_number); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('agency_id')); ?>:</b>
	<?php echo CHtml::encode($data->travelAgencyName); ?>
	<br />
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('paymment_type')); ?>:</b>
	<?php echo CHtml::encode($data->getPaymmentTypeName()); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('pax')); ?>:</b>
	<?php echo CHtml::encode($data->pax); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('activity_id')); ?>:</b>
	<?php echo CHtml::encode($data->activity_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('value_payed')); ?>:</b>
	<?php echo CHtml::encode($data->value_payed); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('notes')); ?>:</b>
	<?php echo CHtml::encode($data->notes); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_time')); ?>:</b>
	<?php echo CHtml::encode($data->create_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_time')); ?>:</b>
	<?php echo CHtml::encode($data->update_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('country')); ?>:</b>
	<?php echo CHtml::encode($data->country_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('number_children')); ?>:</b>
	<?php echo CHtml::encode($data->number_children); ?>
	<br />

	*/ ?>

</div>

protected/views/client/admin.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Client', 'url'=>array('index')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('client-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Clients</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'client-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'name',
		'telephone',
		'email',
		'pax',
		array(
			'name'=>'totalDirect',
			'value'=>'$data->totalDirect',
			'filter'=>false
		),
		array(
			'name'=>'totalCredit',
			'value'=>'$data->totalCredit',
			'filter'=>false
		),
		array(
			'class'=>'CButtonColumn',
			'header'=>'Options',
		),
	),
)); ?>

protected/views/client/create.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Client', 'url'=>array('index')),
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<h1>Create Client</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model, 
												'agencies'=>$agencies,
												'hotels'=>$hotels)); 
?>

protected/views/client/index.php
<?php
$this->breadcrumbs=array(
	'Clients',
);

$this->menu=array(
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<h1>Clients</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/client/move.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Move',
);

$this->menu=array(
	array('label'=>'List Client', 'url'=>array('index')),
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<div class="info">
<h3><?php echo Yii::t('UI', 'Select a Activity from the list below to copy/move' .
		' "clientName" to ', array('clientName'=>$model->name)); ?></h3>

</div>
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'move-client-form',
	'enableAjaxValidation'=>false,
)); ?>

<div class="activity-grid">
		<?php $this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'activity-client-grid',
		'dataProvider'=>$activities,
		'columns'=>array(
			'id',
			array( // display 'Activity.type_id' using an expression
            'name'=>'type_id',
            'value'=>'$data->type->name',
        ),
			'date',
			'time',
			
      
      array( // Display a column with available seats
      	'name'=> Yii::t('UI', 'Availabe Seats'),
      	'value'=>'$data->getAvailableSeats()',
      ),
      
			array(
			'class'=>'CButtonColumn',
			'template'=>'{view}{add}{move}',
			
			'viewButtonUrl'=>'Yii::app()->createUrl("/client/view", array("id"=>$data["id"]))',
			'viewButtonLabel'=> Yii::t('ToolTips', 'View Client'),
			
			// Move button
			'buttons'=> array(
				'add'=>array(
						'label'=>Yii::t('ToolTips', 'Copy to this Activiy'),
						'imageUrl'=> Yii::app()->baseUrl.'/images/list-add.png',
						'url'=>'Yii::app()->createUrl(' .
								'"/client/copyToActivity", ' .
								'array(' .
									'"id"=>'."$model->id".', ' .
									'"newActivityId"=>$data["id"], ' .
									'"activityId"=>'."$activityId".'))',
					),
				'move'=>array(
						'label'=>Yii::t('ToolTips', ' Move to this Actvivity'),
						'imageUrl'=> Yii::app()->baseUrl.'/images/object-rotate-right.png',
						'url'=>'Yii::app()->createUrl(' .
								'"/client/moveToActivity", ' .
								'array("id"=>'."$model->id".', ' .
								'"newActivityId"=>$data["id"],' .
								'"activityId"=>'."$activityId".'))',
					)
			),
		),
	))); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/client/update.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Client', 'url'=>array('index')),
	array('label'=>'View Client', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<h1>Update Client <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',  array('model'=>$model,
												'agencies'=>$agencies,
												'hotels'=>$hotels));  ?>

protected/views/client/view.php
<?php
$this->breadcrumbs=array(
	'Clients'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Client', 'url'=>array('index')),
	array('label'=>'Update Client', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Client', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<h1>View Client #<?php echo $model->id; ?></h1>

<?php $this->widget('TDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'telephone',
		'email',
		array(
			'name'=>'hotel_id',
			'value'=>CHtml::encode($model->getHotelName())
		),
		'room_number',
		array(
			'name'=>'travel_agency',
			'value'=>CHtml::encode($model->getTravelAgencyName())
		),
		'voucher',
		'pax',
		'number_children',
		'value_payed_adult',
		'value_payed_children',
		'value_prepayed',
		'notes',
		array(
			'name'=>'country_id',
			'value'=>CHtml::encode($model->getCountryName())
		),
		array(
			'name'=>'paymment_type',
			'value'=>CHtml::encode($model->getPaymmentTypeName())
		),
		array(
			'name'=>'Total Direct',
			'value'=>CHtml::encode($model->getTotalDirect()),
		),
		array(
			'name'=>'Total Credit',
			'value'=>CHtml::encode($model->getTotalCredit()),
		),

		array(
			'name'=>'Debt',
			'value'=>$model->getDebt(),
		),
		'arrived'
	)
)); ?>